---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id: copykernel
  module: shellprocess
  config: shellprocess-copykernel.conf
- id: fixinitcpio
  module: shellprocess
  config: shellprocess-fixinitcpio.conf
- id: cleanup
  module: shellprocess
  config: shellprocess-cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - shellprocess@copykernel
  - shellprocess@fixinitcpio
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - packages
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: lyra
prompt-install: true
dont-chroot: false
