---
dontChroot: false
timeout: 60
script:
    - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
    - "rm -f /etc/mkinitcpio.d/archiso.preset"
    - "sed 's|%PKGBASE%|linux|g' /usr/share/mkinitcpio/hook.preset > /etc/mkinitcpio.d/linux.preset"
