---
defaultGroups:
    - users
    - wheel
    - audio
    - video
    - storage
    - lp
    - scanner
    - power
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: false
passwordRequirements:
    minLength: 4
    nonempty: true
user:
    shell: /bin/bash
    forbidden_names: [ root, lyra ]
