[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=xfce
session-wrapper=/etc/lightdm/Xsession
autologin-user=lyra
autologin-user-timeout=0
autologin-session=xfce
